services:

  # Backend
  workspaces-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      TASK_DATABASE_URL: postgresql+asyncpg://workspaces-tasks-${ENV}:${WS_TASKS_DB_PASS}@opensidewalks-${ENV}.postgres.database.azure.com:5432/workspaces-tasks-${ENV}      
      OSM_DATABASE_URL: postgresql+asyncpg://workspaces-osm-${ENV}:${WS_OSM_DB_PASS}@opensidewalks-${ENV}.postgres.database.azure.com:5432/workspaces-osm-${ENV}      

  # C-accelerated OSM API
  osm-cgimap:
    build:
      context: workspaces-cgimap
      dockerfile: docker/ubuntu/Dockerfile2404
    restart: always
    environment:
      CGIMAP_INSTANCES: 10
      CGIMAP_HOST: opensidewalks-${ENV}.postgres.database.azure.com
      CGIMAP_USERNAME: workspaces-osm-${ENV}
      CGIMAP_PASSWORD: ${WS_OSM_DB_PASS}
      CGIMAP_DBNAME: workspaces-osm-${ENV}
      CGIMAP_MAX_CHANGESET_ELEMENTS: 100000000 # max features per import or save
      CGIMAP_MAX_PAYLOAD: 1000000000 # max size of dataset uploads
      CGIMAP_MAP_NODES: 100000000 # max number of nodes per requeset
      CGIMAP_MAP_AREA: 1 # max area per request in square degrees

  # Rails OSM API
  osm-rails:
    build:
      context: workspaces-openstreetmap-website
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${WS_OSM_SECRET_KEY_BASE}
      WS_OSM_DB_HOST: opensidewalks-${ENV}.postgres.database.azure.com
      WS_OSM_DB_USER: workspaces-osm-${ENV}
      WS_OSM_DB_PASS: ${WS_OSM_DB_PASS}
      WS_OSM_DB_NAME: workspaces-osm-${ENV}
    volumes:
        - /tmp:/tmp
        - /tmp:/app/tmp
        - /tmp/storage:/app/storage
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  
  osm-rails-worker:
      build:
        context: workspaces-openstreetmap-website
        dockerfile: Dockerfile.prod
      restart: always
      environment:
        RAILS_ENV: production
        SECRET_KEY_BASE: ${WS_OSM_SECRET_KEY_BASE}
        WS_OSM_DB_HOST: opensidewalks-${ENV}.postgres.database.azure.com
        WS_OSM_DB_USER: workspaces-osm-${ENV}
        WS_OSM_DB_PASS: ${WS_OSM_DB_PASS}
        WS_OSM_DB_NAME: workspaces-osm-${ENV}
      volumes:
        - /tmp:/tmp
        - /tmp:/app/tmp
        - /tmp/storage:/app/storage
      stdin_open: true
      tty: true
      command: bundle exec rake jobs:work