"""workspace import status

Revision ID: aa17ec83af0d
Revises: d4e8f1a92b56
Create Date: 2026-08-13 04:58:59.982773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aa17ec83af0d"
down_revision: Union[str, None] = "d4e8f1a92b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspaces", sa.Column("importStatus", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "importStatus")
    # ### end Alembic commands ###
