"""added flag for conflict override

Revision ID: c93bbbfd4279
Revises: aa17ec83af0d
Create Date: 2026-08-27 16:34:41.436834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c93bbbfd4279'
down_revision: Union[str, None] = 'aa17ec83af0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('override_conflicts', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('workspaces', 'override_conflicts')
    # ### end Alembic commands ###
